[package]
name = "config-builder"
version = "0.1.0"
authors = ["Nemurimasu Neiro <nemurimasu@gmail.com>"]
edition = "2018"

[dependencies]
jsonpath_lib = "0.2"
serde = "1"
serde_json = "1"
quick-xml = "0.14"
yaml-rust = "0.4"
