#cloud-config
disk_setup:
  ephemeral0:
    table_type: mbr
    layout: [[100, 82]]
    overwrite: True
fs_setup:
- device: ephemeral0.1
  filesystem: swap
mounts:
- ["ephemeral0.1", "none", "swap", "sw", "0", "0"]
packages:
- curl
- gcc
- icecast2
write_files:
- path: /etc/default/icecast2
  content: |
    CONFIGFILE="/etc/icecast2/icecast.xml"
    USERID=icecast2
    GROUPID=icecast
    ENABLE=true
- path: /etc/icecast2/icecast.xml
  content: |
    <icecast>
      <location>Earth</location>
      <admin>icemaster@localhost</admin>
      <limits>
        <clients>100</clients>
        <sources>2</sources>
        <queue-size>524288</queue-size>
        <client-timeout>30</client-timeout>
        <header-timeout>15</header-timeout>
        <source-timeout>10</source-timeout>
        <burst-on-connect>1</burst-on-connect>
        <burst-size>65535</burst-size>
      </limits>
      <authentication>
        <source-password><!--source-password--></source-password>
        <relay-password><!--relay-password--></relay-password>
        <admin-user>admin</admin-user>
        <admin-password><!--admin-password--></admin-password>
      </authentication>
      <hostname>localhost</hostname>
      <listen-socket>
        <port>8000</port>
      </listen-socket>
      <http-headers>
        <header name="Access-Control-Allow-Origin" value="*" />
      </http-headers>
      <fileserve>1</fileserve>
      <paths>
        <basedir>/usr/share/icecast2</basedir>
        <logdir>/var/log/icecast2</logdir>
        <webroot>/usr/share/icecast2/web</webroot>
        <adminroot>/usr/share/icecast2/admin</adminroot>
        <alias source="/" destination="/status.xsl"/>
      </paths>
      <logging>
        <accesslog>access.log</accesslog>
        <errorlog>error.log</errorlog>
        <loglevel>3</loglevel>
        <logsize>10000</logsize>
      </logging>
      <security>
        <chroot>0</chroot>
      </security>
    </icecast>
- path: /etc/systemd/system/ingress.service
  content: |
    [Unit]
    Description=Stream Share Ingress
    [Service]
    ExecStart=/usr/local/bin/ingress
    [Install]
    WantedBy=mult-user.target
runcmd:
- [ "sh", "-c", "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y" ]
- [ "sh", "-c", "mkdir stream-share && curl --proto '=https' --tlsv1.2 -sSfL https://github.com/nemurimasu/stream-share/tarball/master | tar xz -C stream-share --strip-components=1" ]
- [ "/root/.cargo/bin/cargo", "build", "--release", "--manifest-path", "stream-share/Cargo.toml", "-p", "ingress" ]
- [ "install", "stream-share/target/release/ingress", "/usr/local/bin/ingress" ]
- [ "systemctl", "daemon-reload" ]
- [ "systemctl", "enable", "--now", "ingress" ]
